{{- if .Values.ingress.enabled }}
{{- $fullname := include "aidetect.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "aidetect.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.api }}
        - {{ .Values.ingress.hosts.app }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.hosts.api }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-backend
                port:
                  number: 80
    - host: {{ .Values.ingress.hosts.app }}
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-frontend
                port:
                  number: 80
{{- end }}
